apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/wlgns5376/example-app
  newTag: e70be61b
patchesStrategicMerge:
- configmap.yaml
- secret.yaml
resources:
- ../../base
