apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
- name: ghcr.io/wlgns5376/example-app
  newTag: 4c27ecad
patchesStrategicMerge:
- configmap.yaml
- secret.yaml