apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/wlgns5376/example-app
  newTag: 66ff1612
patchesStrategicMerge:
- configmap.yaml
- secret.yaml
resources:
- ../../base
