apiVersion: v1
kind: Secret
metadata:
  name: example-app-secret
  labels:
    app: example-app
type: Opaque
data:
  DB_USERNAME: aG9tZXN0ZWFk # echo -n "homestead" | base64
  DB_PASSWORD: c2VjcmV0 # echo -n "secret" | base64
  DB_ROOT_PASSWORD: c2VjcmV0 # echo -n "secret" | base64